Description of divNonUniform
divNonUniform
PURPOSE
Returns a m+2 by m+1 one-dimensional non-uniform mimetic divergence
SYNOPSIS
function D = divNonUniform(k, ticks)
DESCRIPTION
 Returns a m+2 by m+1 one-dimensional non-uniform mimetic divergence
 operator
 Parameters:
                k : Order of accuracy
                ticks : Edges' ticks e.g. [0 0.1 0.15 0.2 0.3 0.4 0.45]
CROSS-REFERENCE INFORMATION
This function calls:
div Returns a m+2 by m+1 one-dimensional mimetic divergence operator
This function is called by:
div2DNonUniform Returns a two-dimensional non-uniform mimetic divergence operator
div3DNonUniform Returns a three-dimensional non-uniform mimetic divergence operator
SOURCE CODE
function D = divNonUniform(k, ticks)
% Returns a m+2 by m+1 one-dimensional non-uniform mimetic divergence
% operator
%
% Parameters:
%                k : Order of accuracy
%                ticks : Edges' ticks e.g. [0 0.1 0.15 0.2 0.3 0.4 0.45]
    % Get uniform operator without scaling
    D = div(k, length(ticks)-1, 1);
    [m, ~] = size(D);
    % Compute the Jacobian using the uniform operator and the ticks
    if size(ticks, 1) == 1
        J = spdiags((D*ticks').^-1, 0, m, m);
    else
        J = spdiags((D*ticks).^-1, 0, m, m);
    end
    % This is the non-uniform operator
    D = J*D;
end