Description of grad2D
grad2D
PURPOSE
Returns a two-dimensional mimetic gradient operator
SYNOPSIS
function G = grad2D(k, m, dx, n, dy)
DESCRIPTION
 Returns a two-dimensional mimetic gradient operator
 Parameters:
                k : Order of accuracy
                m : Number of cells along x-axis
               dx : Step size along x-axis
                n : Number of cells along y-axis
               dy : Step size along y-axis
CROSS-REFERENCE INFORMATION
This function calls:
grad Returns a m+1 by m+2 one-dimensional mimetic gradient operator
This function is called by:
grad2DCurv Get the determinant of the jacobian and the metrics
lap2D Returns a two-dimensional mimetic laplacian operator
SOURCE CODE
function G = grad2D(k, m, dx, n, dy)
% Returns a two-dimensional mimetic gradient operator
%
% Parameters:
%                k : Order of accuracy
%                m : Number of cells along x-axis
%               dx : Step size along x-axis
%                n : Number of cells along y-axis
%               dy : Step size along y-axis
    Gx = grad(k, m, dx);
    Gy = grad(k, n, dy);
    Im = sparse(m + 2, m);
    In = sparse(n + 2, n);
    Im(2:(m+2)-1, :) = speye(m, m);
    In(2:(n+2)-1, :) = speye(n, n);
    Sx = kron(In', Gx);
    Sy = kron(Gy, Im');
    G = [Sx; Sy];
end