Description of mimeticB
mimeticB
PURPOSE
Returns a m+2 by m+1 one-dimensional mimetic boundary operator
SYNOPSIS
function B = mimeticB(k, m)
DESCRIPTION
 Returns a m+2 by m+1 one-dimensional mimetic boundary operator
 Parameters:
                k : Order of accuracy
                m : Number of cells
CROSS-REFERENCE INFORMATION
This function calls:
div Returns a m+2 by m+1 one-dimensional mimetic divergence operator
grad Returns a m+1 by m+2 one-dimensional mimetic gradient operator
weightsP Returns the m+1 weights of P
weightsQ Returns the m+2 weights of Q
This function is called by:
SOURCE CODE
function B = mimeticB(k, m)
% Returns a m+2 by m+1 one-dimensional mimetic boundary operator
%
% Parameters:
%                k : Order of accuracy
%                m : Number of cells
    Q = sparse(diag(weightsQ(k, m, 1)));
    D = div(k, m, 1);
    G = grad(k, m, 1);
    P = sparse(diag(weightsP(k, m, 1)));
    B = Q*D + G'*P;
end