Description of nodal
nodal
PURPOSE
Returns a m+1 by m+1 one-dimensional operator that approximates the
SYNOPSIS
function N = nodal(k, m, dx)
DESCRIPTION
 Returns a m+1 by m+1 one-dimensional operator that approximates the
 first-order derivatives on a uniform nodal grid
 Parameters:
                k : Order of accuracy
                m : Number of nodes
               dx : Step size
CROSS-REFERENCE INFORMATION
This function calls:
grad Returns a m+1 by m+2 one-dimensional mimetic gradient operator
This function is called by:
grad Returns a m+1 by m+2 one-dimensional mimetic gradient operator
nodal2D Returns a two-dimensional operator that approximates the first-order
nodal3D Returns a three-dimensional operator that approximates the first-order
SOURCE CODE
function N = nodal(k, m, dx)
% Returns a m+1 by m+1 one-dimensional operator that approximates the
% first-order derivatives on a uniform nodal grid
%
% Parameters:
%                k : Order of accuracy
%                m : Number of nodes
%               dx : Step size
    N = grad(k, m-1, dx, 'nodal');
end