Description of robinBC
robinBC
PURPOSE
Returns a m+2 by m+2 one-dimensional mimetic boundary operator that
SYNOPSIS
function BC = robinBC(k, m, dx, a, b)
DESCRIPTION
 Returns a m+2 by m+2 one-dimensional mimetic boundary operator that
 imposes a boundary condition of Robin's type
 Parameters:
                k : Order of accuracy
                m : Number of cells
               dx : Step size
                a : Dirichlet Coefficient
                b : Neumann Coefficient
CROSS-REFERENCE INFORMATION
This function calls:
grad Returns a m+1 by m+2 one-dimensional mimetic gradient operator
This function is called by:
robinBC2D Returns a two-dimensional mimetic boundary operator that
robinBC3D Returns a three-dimensional mimetic boundary operator that
SOURCE CODE
function BC = robinBC(k, m, dx, a, b)
% Returns a m+2 by m+2 one-dimensional mimetic boundary operator that
% imposes a boundary condition of Robin's type
%
% Parameters:
%                k : Order of accuracy
%                m : Number of cells
%               dx : Step size
%                a : Dirichlet Coefficient
%                b : Neumann Coefficient
    A = sparse(m+2, m+2);
    A(1, 1) = a;
    A(end, end) = a;
    B = sparse(m+2, m+1);
    B(1, 1) = -b;
    B(end, end) = b;
    G = grad(k, m, dx);
    BC = A + B*G;
end