Description of weightsP
weightsP
PURPOSE
Returns the m+1 weights of P
SYNOPSIS
function P = weightsP(k, m, dx)
DESCRIPTION
 Returns the m+1 weights of P
 Parameters:
                k : Order of accuracy
                m : Number of cells
               dx : Step size
CROSS-REFERENCE INFORMATION
This function calls:
grad Returns a m+1 by m+2 one-dimensional mimetic gradient operator
This function is called by:
mimeticB Returns a m+2 by m+1 one-dimensional mimetic boundary operator
weightsP2D Returns the 2mn+m+n weights of P in 2-D
SOURCE CODE
function P = weightsP(k, m, dx)
% Returns the m+1 weights of P
%
% Parameters:
%                k : Order of accuracy
%                m : Number of cells
%               dx : Step size
    G = grad(k, m, dx);
    b = [-1; zeros(m, 1); 1]; % RHS
    P = G'\b;
end